# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20171026_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toutiao',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='编号')),
                ('image_url', models.URLField(null=True, verbose_name='图片地址')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('media_creator_id', models.CharField(max_length=254, verbose_name='作者编号')),
                ('media_name', models.CharField(max_length=254, verbose_name='作者昵称')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
